-- mysql script generated by mysql workbench
-- sun may 27 22:12:57 2018
-- model: new model    version: 1.0
-- mysql workbench forward engineering

set @old_unique_checks=@@unique_checks, unique_checks=0;
set @old_foreign_key_checks=@@foreign_key_checks, foreign_key_checks=0;
set @old_sql_mode=@@sql_mode, sql_mode='traditional,allow_invalid_dates';

-- -----------------------------------------------------
-- schema hinode
-- -----------------------------------------------------

-- -----------------------------------------------------
-- schema hinode
-- -----------------------------------------------------
create schema if not exists `hinode` default character set utf8 ;
use `hinode` ;

-- -----------------------------------------------------
-- table `hinode`.`pais`
-- -----------------------------------------------------
create table if not exists `hinode`.`pais` (
  `id` int not null auto_increment,
  `nome` varchar(55) not null,
  `cod_pais` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc))
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`estado`
-- -----------------------------------------------------
create table if not exists `hinode`.`estado` (
  `id` int not null auto_increment,
  `sigla` varchar(2) not null,
  `nome` varchar(30) not null,
  `cod_estado` int not null,
  `pais_id` int null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_estado_pais_idx` (`pais_id` asc),
  constraint `fk_estado_pais`
    foreign key (`pais_id`)
    references `hinode`.`pais` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`cidade`
-- -----------------------------------------------------
create table if not exists `hinode`.`cidade` (
  `id` int not null auto_increment,
  `nome` varchar(45) not null,
  `cod_cidade` int not null,
  `estado_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_cidade_estado1_idx` (`estado_id` asc),
  constraint `fk_cidade_estado1`
    foreign key (`estado_id`)
    references `hinode`.`estado` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`endereco`
-- -----------------------------------------------------
create table if not exists `hinode`.`endereco` (
  `id` int not null auto_increment,
  `cep` varchar(8) not null,
  `bairro` varchar(45) not null,
  `endereco` varchar(55) not null,
  `numero` varchar(6) null,
  `complemento` varchar(60) null,
  `pais_id` int not null,
  `estado_id` int not null,
  `cidade_id` int not null,
  index `fk_endereco_pais1_idx` (`pais_id` asc),
  index `fk_endereco_estado1_idx` (`estado_id` asc),
  index `fk_endereco_cidade1_idx` (`cidade_id` asc),
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  constraint `fk_endereco_pais1`
    foreign key (`pais_id`)
    references `hinode`.`pais` (`id`)
    on delete no action
    on update no action,
  constraint `fk_endereco_estado1`
    foreign key (`estado_id`)
    references `hinode`.`estado` (`id`)
    on delete no action
    on update no action,
  constraint `fk_endereco_cidade1`
    foreign key (`cidade_id`)
    references `hinode`.`cidade` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`contato`
-- -----------------------------------------------------
create table if not exists `hinode`.`contato` (
  `id` int not null auto_increment,
  `telefone` varchar(10) null,
  `celular` varchar(11) not null,
  `email` varchar(45) not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  unique index `email_unique` (`email` asc))
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`pessoa`
-- -----------------------------------------------------
create table if not exists `hinode`.`pessoa` (
  `id` int not null auto_increment,
  `contato_id` int not null,
  `endereco_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_pessoa_contato1_idx` (`contato_id` asc),
  index `fk_pessoa_endereco1_idx` (`endereco_id` asc),
  unique index `contato_id_unique` (`contato_id` asc),
  unique index `endereco_id_unique` (`endereco_id` asc),
  constraint `fk_pessoa_contato1`
    foreign key (`contato_id`)
    references `hinode`.`contato` (`id`)
    on delete no action
    on update no action,
  constraint `fk_pessoa_endereco1`
    foreign key (`endereco_id`)
    references `hinode`.`endereco` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`usuario`
-- -----------------------------------------------------
create table if not exists `hinode`.`usuario` (
  `id` int not null auto_increment,
  `login` varchar(30) not null,
  `senha` varchar(64) not null,
  `data_criacao` timestamp default current_timestamp,
  `data_alteracao` timestamp default current_timestamp,
  `pessoa_id` int not null,
  primary key (`id`),
  index `fk_usuario_pessoa1_idx` (`pessoa_id` asc),
  unique index `pessoa_id_unique` (`pessoa_id` asc),
  unique index `login_unique` (`login` asc),
  constraint `fk_usuario_pessoa1`
    foreign key (`pessoa_id`)
    references `hinode`.`pessoa` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`cliente`
-- -----------------------------------------------------
create table if not exists `hinode`.`cliente` (
  `id` int not null auto_increment,
  `criado_por` int not null,
  `data_criacao` timestamp default current_timestamp,
  `alterado_por` int not null,
  `data_alteracao` timestamp default current_timestamp,
  `pessoa_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_cliente_pessoa1_idx` (`pessoa_id` asc),
  index `fk_cliente_usuario1_idx` (`criado_por` asc),
  index `fk_cliente_usuario2_idx` (`alterado_por` asc),
  unique index `pessoa_id_unique` (`pessoa_id` asc),
  constraint `fk_cliente_pessoa1`
    foreign key (`pessoa_id`)
    references `hinode`.`pessoa` (`id`)
    on delete no action
    on update no action,
  constraint `fk_cliente_usuario1`
    foreign key (`criado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action,
  constraint `fk_cliente_usuario2`
    foreign key (`alterado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`pessoa_fisica`
-- -----------------------------------------------------
create table if not exists `hinode`.`pessoa_fisica` (
  `id` int not null auto_increment,
  `rg` varchar(9) not null,
  `cpf` varchar(11) not null,
  `nome` varchar(60) not null,
  `data_nascimento` date not null,
  `pessoa_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  unique index `cpf_unique` (`cpf` asc),
  index `fk_pessoa_fisica_pessoa1_idx` (`pessoa_id` asc),
  unique index `pessoa_id_unique` (`pessoa_id` asc),
  unique index `rg_unique` (`rg` asc),
  constraint `fk_pessoa_fisica_pessoa1`
    foreign key (`pessoa_id`)
    references `hinode`.`pessoa` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`pessoa_juridica`
-- -----------------------------------------------------
create table if not exists `hinode`.`pessoa_juridica` (
  `id` int not null auto_increment,
  `cnpj` varchar(14) not null,
  `razao_social` varchar(50) not null,
  `fantasia` varchar(50) not null,
  `inscricao_estadual` varchar(9) not null,
  `pessoa_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  unique index `cnpj_unique` (`cnpj` asc),
  index `fk_pessoa_juridica_pessoa1_idx` (`pessoa_id` asc),
  unique index `pessoa_id_unique` (`pessoa_id` asc),
  constraint `fk_pessoa_juridica_pessoa1`
    foreign key (`pessoa_id`)
    references `hinode`.`pessoa` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`forma_pagamento`
-- -----------------------------------------------------
create table if not exists `hinode`.`forma_pagamento` (
  `id` int not null auto_increment,
  `descricao` varchar(45) not null,
  `juros` smallint not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc))
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`pedido`
-- -----------------------------------------------------
create table if not exists `hinode`.`pedido` (
  `id` int not null auto_increment,
  `data_pedido` timestamp default current_timestamp,
  `valor_pedido` decimal(10,2) not null,
  `forma_pagamento_id` int not null,
  `encomendado_por` int not null,
  `despachado_por` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_pedido_cliente1_idx` (`encomendado_por` asc),
  index `fk_pedido_usuario1_idx` (`despachado_por` asc),
  index `fk_pedido_forma_pagamento1_idx` (`forma_pagamento_id` asc),
  constraint `fk_pedido_cliente1`
    foreign key (`encomendado_por`)
    references `hinode`.`cliente` (`id`)
    on delete no action
    on update no action,
  constraint `fk_pedido_usuario1`
    foreign key (`despachado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action,
  constraint `fk_pedido_forma_pagamento1`
    foreign key (`forma_pagamento_id`)
    references `hinode`.`forma_pagamento` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`categoria`
-- -----------------------------------------------------


create table if not exists `hinode`.`categoria` (
  `id` int not null auto_increment,
  `descricao` varchar(30) not null,
  `direita` int not null,
  `esquerda` int not null,
  `data_criacao` timestamp default current_timestamp,
  `data_alteracao` timestamp default current_timestamp,
  `categoria_pai_id` int null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_categoria_categoria1_idx` (`categoria_pai_id` asc),
  constraint `fk_categoria_categoria1`
    foreign key (`categoria_pai_id`)
    references `hinode`.`categoria` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`produto`
-- -----------------------------------------------------
create table if not exists `hinode`.`produto` (
  `id` int not null auto_increment,
  `codigo_produto` varchar(25) not null,
  `nome` varchar(50) not null,
  `descricao` text null,
  `quantidade_estoque` smallint not null,
  `valor_compra` decimal(10,2) not null,
  `valor_venda` decimal(10,2) not null,
  `caminho_imagem` varchar(200) null,
  `criado_por` int not null,
  `data_criacao` timestamp default current_timestamp,
  `alterado_por` int not null,
  `data_alteracao` timestamp default current_timestamp,
  `categoria_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  unique index `codigo_produto_unique` (`codigo_produto` asc),
  index `fk_produto_usuario1_idx` (`criado_por` asc),
  index `fk_produto_usuario2_idx` (`alterado_por` asc),
  index `fk_produto_categoria1_idx` (`categoria_id` asc),
  constraint `fk_produto_usuario1`
    foreign key (`criado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action,
  constraint `fk_produto_usuario2`
    foreign key (`alterado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action,
  constraint `fk_produto_categoria1`
    foreign key (`categoria_id`)
    references `hinode`.`categoria` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`pedido_produto`
-- -----------------------------------------------------
create table if not exists `hinode`.`pedido_produto` (
  `id` int not null auto_increment,
  `quantidade` smallint not null,
  `pedido_id` int not null,
  `produto_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_pedido_produto_pedido1_idx` (`pedido_id` asc),
  index `fk_pedido_produto_produto1_idx` (`produto_id` asc),
  constraint `fk_pedido_produto_pedido1`
    foreign key (`pedido_id`)
    references `hinode`.`pedido` (`id`)
    on delete no action
    on update no action,
  constraint `fk_pedido_produto_produto1`
    foreign key (`produto_id`)
    references `hinode`.`produto` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`parcela`
-- -----------------------------------------------------
create table if not exists `hinode`.`parcela` (
  `id` int not null auto_increment,
  `data_vencimento` date not null,
  `data_pagamento` date null,
  `pedido_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_parcela_pedido1_idx` (`pedido_id` asc),
  constraint `fk_parcela_pedido1`
    foreign key (`pedido_id`)
    references `hinode`.`pedido` (`id`)
    on delete no action
    on update no action)
engine = innodb;


-- -----------------------------------------------------
-- table `hinode`.`colaborador`
-- -----------------------------------------------------
create table if not exists `hinode`.`colaborador` (
  `id` int not null auto_increment,
  `criado_por` int not null,
  `data_criacao` timestamp default current_timestamp,
  `alterado_por` int not null,
  `data_alteracao` timestamp default current_timestamp,
  `pessoa_id` int not null,
  primary key (`id`),
  unique index `id_unique` (`id` asc),
  index `fk_colaborador_pessoa1_idx` (`pessoa_id` asc),
  index `fk_colaborador_usuario1_idx` (`criado_por` asc),
  index `fk_colaborador_usuario2_idx` (`alterado_por` asc),
  unique index `pessoa_id_unique` (`pessoa_id` asc),
  constraint `fk_colaborador_pessoa1`
    foreign key (`pessoa_id`)
    references `hinode`.`pessoa` (`id`)
    on delete no action
    on update no action,
  constraint `fk_colaborador_usuario1`
    foreign key (`criado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action,
  constraint `fk_colaborador_usuario2`
    foreign key (`alterado_por`)
    references `hinode`.`usuario` (`id`)
    on delete no action
    on update no action)
engine = innodb;


set sql_mode=@old_sql_mode;
set foreign_key_checks=@old_foreign_key_checks;
set unique_checks=@old_unique_checks;